Update features.py
Fixed:
ValueError: Samples can not be a single string. The input must be an iterable over iterables of strings.

By:
entry_name_hashed = FeatureHasher(50, input_type="string").transform([raw_obj['entry']]).toarray()[0] 
with:
entry_name_hashed = FeatureHasher(50, input_type="string").transform([ [raw_obj['entry']] ]).toarray()[0] 

at line 192.

In this way an iterable over iterable over raw features is obtained, as transform() method require.